### ISSUE TITLE
[meta] Ship 30 languages

### ISSUE THREAD

**Issue by gregtatum** [mozilla/firefox-translations-training#369]
There are some specific meta bugs around of issues around [pipeline usability](https://github.com/mozilla/firefox-translations-training/issues/311), [general translation quality](https://github.com/mozilla/firefox-translations-training/issues/216), and [robustness](https://github.com/mozilla/firefox-translations-training/issues/238), but this meta bug is specifically about blockers around scaling to training and shipping 30 languages. These should be tasks that only the translations team should handle.

```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/firefox-translations-training/issues/143
- [ ] https://github.com/mozilla/firefox-translations-training/issues/450
- [ ] https://github.com/mozilla/firefox-translations-training/issues/505
- [ ] https://github.com/mozilla/firefox-translations-training/issues/503
- [ ] https://github.com/mozilla/firefox-translations-training/issues/210
- [ ] https://github.com/mozilla/firefox-translations-training/issues/528
- [ ] https://github.com/mozilla/firefox-translations-training/issues/472
- [ ] https://github.com/mozilla/firefox-translations-training/issues/544
- [ ] https://github.com/mozilla/firefox-translations-training/issues/274
- [ ] https://github.com/mozilla/firefox-translations-training/issues/371
- [ ] https://github.com/mozilla/firefox-translations-training/issues/456
- [ ] https://github.com/mozilla/firefox-translations-training/issues/388
- [ ] https://github.com/mozilla/firefox-translations-training/issues/411
- [ ] https://github.com/mozilla/firefox-translations-training/issues/55
- [ ] https://github.com/mozilla/firefox-translations-training/issues/360
- [ ] https://github.com/mozilla/firefox-translations-training/issues/314
- [ ] https://github.com/mozilla/firefox-translations-training/issues/293
- [ ] https://github.com/mozilla/firefox-translations-training/issues/292
- [ ] https://github.com/mozilla/firefox-translations-training/issues/272
- [x] Update the prod.config.yml with augmented datasets
```
