### ISSUE TITLE
[meta] issues before primary maintance of taskgraph code in this repository is handed off to translations engineers

### ISSUE THREAD

**Issue by bhearsum** [mozilla/firefox-translations-training#490]
This list is for things that RelEng needs to take care of before we take a step back from active involvement in this project.

- [ ] https://github.com/mozilla/firefox-translations-training/issues/487
- [ ] https://github.com/mozilla/firefox-translations-training/issues/473
- [ ] https://github.com/mozilla/firefox-translations-training/issues/466
- [ ] https://github.com/mozilla/firefox-translations-training/issues/375
- [ ] https://github.com/mozilla/firefox-translations-training/issues/300
- [ ] https://github.com/mozilla/firefox-translations-training/issues/391
- [ ] https://github.com/mozilla/firefox-translations-training/issues/618
- [ ] https://github.com/mozilla/firefox-translations-training/issues/640
- [ ] https://github.com/mozilla/firefox-translations-training/issues/653
- [ ] https://github.com/mozilla/firefox-translations-training/issues/710

**Comment by bhearsum** [comment]
Between this and #311 there are a fairly hefty number of issues related to Taskcluster with various dependencies between them. I created [a simple diagram with dependencies and current status](https://raw.githubusercontent.com/bhearsum/firefox-translations-training/issues/taskcluster-related-issues.mm.svg) to hopefully help with this, which I will try to keep up to date.
